### ISSUE TITLE
List of Illustrations that match buidling type

### ISSUE THREAD

**Issue by sohilpandya** [InFact-coop/building-exploratory#27]
Hi @nogainbar,

Can you please list the building types that fit each of the seven illustrations we have down below please. 

Thanks! :)

**Comment by nogainbar** [comment]
Hey @sohilpandya!
I checked and each illustration should have the type of building in the file name, so you should be able to match the type with the image:

Education Building
Home
Industrial building
Other historic structure
Place of Worship
Public building
Shop

**Comment by jessicasalmon** [comment]
Hi @nogainbar, we're still having difficulty with the images as it is not clear which illustration should map to which building type. 

A simple example of this is 'Industrial building' which could be 'Warehouse' or 'Factory and Warehouse'.

Do you have a list of of the building types which should match each illustration? We need this list in order to map the illustrations to buildings types correctly.

**Comment by jessicasalmon** [comment]
After chatting with @nogainbar we understand that a new column will need to be added to the spreadsheet and each item in the database will need to have one of the 7 categories attached, as the current categories in building type do not match up exactly to the provided category list. Closing now :)
