### ISSUE TITLE
Details view: add more margin to the top

### ISSUE THREAD

**Issue by jessicasalmon** [InFact-coop/building-exploratory#52]
## Description
View: building details page
Issue: difference in space above titles is larger elsewhere than above the 'description' field 

## Screenshot
<img width="714" alt="screen shot 2018-01-17 at 16 55 44" src="https://user-images.githubusercontent.com/19147734/35055613-79e2ba70-fba7-11e7-85ce-b253e9aeccb9.png">

**Comment by KatieRussellTBE** [comment]
The spacing above the 'Description' field has been addressed and is now fine.
Would it be at all possible to push up all the details text so that there is less white space between the line under the website title and the top of the illustration icon, i.e. so the top of the illustration is in line with the top of the 4 boxes icon on the right?

**Comment by jessicasalmon** [comment]
hey @KatieRussellTBE great that you're happy with the description field update. 

> Would it be at all possible to push up all the details text so that there is less white space between the line under the website title and the top of the illustration icon, i.e. so the top of the illustration is in line with the top of the 4 boxes icon on the right?

Unfortunately, that would be classified as an extra feature. I've created a new issue (#90) for it and put it in the backlog. This means if we carry out work in the future, it can be addressed as part of that scope.

**Comment by KatieRussellTBE** [comment]
OK, thanks - just wanted to check what was possible. Thanks for clarifying.
