### ISSUE TITLE
Inconsistencies in Display of Building Name and Street Name

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#87]
Some thumbnail entries only display the name of the building, and not the street address, but when you click through to the details page, the building name disappears and only the street address is displayed. This happens with The Printworks, Blanch House, Churchill House, Mountford House. But does not happen with Moorfields Eye Hopsital: while only the building name appears in the thumbnail view, the building name and the street address are both displayed on the details page.

**Comment by jessicasalmon** [comment]
Hi @KatieRussellTBE,

The functionality is as discussed when we met and decided to display building names when we had them on the card page and display the street address in the detailed view. 

The reason for the inconsistency with the Moorfield Eye hospital is because the street number field on the dummy google sheet contains `Moorfields Hospital, No. 162 ` which is why it is shown on the details page.

**Comment by KatieRussellTBE** [comment]
Hi @jessicasalmon  - Apologies, I don't remember discussing this and don't seem to have a note of it. Would it be possible to have the name of the building displayed on the details page at least? It seems a little confusing that it disappears on this page.
